CREATE
DATABASE  IF NOT EXISTS demo;
USE
demo;
CREATE TABLE IF NOT EXISTS users
(
    id
    BIGINT
    AUTO_INCREMENT
    PRIMARY
    KEY,
    username
    VARCHAR
(
    100
) NOT NULL UNIQUE,
    email VARCHAR
(
    150
) NOT NULL UNIQUE,
    password VARCHAR
(
    255
) NOT NULL,
    status VARCHAR
(
    50
) DEFAULT 'ACTIVE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
